### ISSUE TITLE
Definir a LICENSE/README e etc

### ISSUE THREAD

**Issue by caio-emidio** [aHub-Tech/hub-site-front#13]
Definir License/Readme e etc... de acordo com as politicas de Arquitetura e Devops da HUB.

**Comment by RodrigoDornelles** [comment]
@vcwild @DevRadhy tasca-le GPL 3.0 em **nosso** site?

**Comment by vcwild** [comment]
Não posso fazer isso, quem define licença é o desenvolvedor do projeto. 

Não existe licença da Hub e a Hub não força ninguém a usar GPLv3.

**Comment by RodrigoDornelles** [comment]
@vcwild o davi e o lucas disseram que tanto faz a licensa... e repassaram para a nós escolhermos isso, enfim se ninguém impor uma licensa pode ser essa. não?  `¯\_(ツ)_/¯`

**Comment by daviprm** [comment]
Na verdade, acho que seria massa, por ser um projeto da "comunidade", deixar pra quem gerencia os projetos decidir a licença...
Conversei com o Caio e Paulo sobre isso, e chegamos a conclusão de que pode ser GPL3!

**Comment by vcwild** [comment]
Reitero que não só é responsabilidade do desenvolvedor fazer escolha da licença, como responsabilidade de arcar com as consequências dessa decisão.

A comunidade está a seu dispor pra ajudar no que precisar, mas jamais vamos tomar de você sua propriedade intelectual em nome de nossa ou de outra associação.

O máximo que podemos é te auxiliar a tomar essa decisão. Mas a escolha em si não deve ser tomada por gestores ou terceiros, apenas quem realmente estiver desenvolvendo/mantendo tem direitos plenos sobre a obra.

**Comment by vcwild** [comment]
> @vcwild o davi e o lucas disseram que tanto faz a licensa... e repassaram para a nós escolhermos isso, enfim se ninguém impor uma licensa pode ser essa. não?  `¯\_(ツ)_/¯`

A menos que queiram alterar nossas políticas internas, vai ficar sem licença até um dos devs a atribuir.

**Comment by vcwild** [comment]
Pessoal, isso é um assunto complicado e que tem diversos desdobramentos éticos e implicações jurídicas. Não se sabe o que pode acontecer daqui 1 semana, 1 mês, 1 ano... Bom, deixei minhas posições aqui como o coordenador dos projetos, caso vocês acharem cabível mudar algum ponto, estou sempre aberto ao diálogo.

**Comment by RodrigoDornelles** [comment]
"Re aberto" ~nossa esse termo em portugues é pouco estranho~, efim, aqui sera discutido sobre documentação também.

**Comment by caio-emidio** [comment]
Acho que ja esta definido que foi GPL3
