### ISSUE TITLE
Tutores - Card

### ISSUE THREAD

**Issue by caio-emidio** [aHub-Tech/hub-site-front#14]
# Projeto de Tutores

Criar Component

![image](https://user-images.githubusercontent.com/5342402/145053910-b91ff0d3-303b-4f5a-a167-b88b52b50211.png)

Esse component deve respeitar algumas regras
o title deve ter a cor de acordo com o alguma tabela que deve ser criada.

## As Cores

```json
{
    "Backend":"#3BF79D",
    "FullStack": "#FFD235",
    "Design": "#FF35D3",
}
```

O mesmo se baseia para os conhecimentos. Isso vai ajudar na busca visual que pessoas possam a vir a ter... 

## Json Example
```json
{
  "title": "FullStack",
  "name": "Davi Mello",
  "photo": "https://github.com/daviprm",
  "IsVerified": true,
  "hasDiploma": true,
  "isMVP": true,
  "resume": {
  "link": "LinkParaOCV"
  }
  "description": "Desenvolvedor full-stack há mais de 5 anos, cursando Engenharia de Software",
  "knowledges": [
    "nodejs",
    "VUEJS",
    "Typescript"
    ],
  "contact": [
      {"name": "instagram", "value": "asdasdasdas"},
      {"name": "twitch", "value": "asdasdasdasd"},
      {"name": "facebook", "value": "asdasdasd"},
      {"name": "instagram", "value": "asdasdasd"},
      {"name": "linkedin", "value": "asdasdasd"},
      {"name": "github", "value": "https://github.com/daviprm"}
      {"name": "discord", "value": "davii#3906"}
    ]
}
```

**Comment by caio-emidio** [comment]
![image](https://user-images.githubusercontent.com/5342402/145056720-85cf0bef-9c1e-4d8d-8c7d-a11d504dc2fb.png)

**Comment by pcbrsites** [comment]
@caio-emidio @daviprm Já pode fechar?

**Comment by caio-emidio** [comment]
Nao foram implementados todos os campos que foi pedido. 
Vou reabrir essa atividade para Janeiro.
