### ISSUE TITLE
Adicionar docker

### ISSUE THREAD

**Issue by RodrigoDornelles** [aHub-Tech/hub-site-front#22]

**Comment by caio-emidio** [comment]
Nao sei se eh uma boa. Acho que a solucao que usamos no pages.dev torna essa issue desnecessaria.

**Comment by RodrigoDornelles** [comment]
> Nao sei se eh uma boa. Acho que a solucao que usamos no pages.dev torna essa issue desnecessaria.

Docker não ajuda só no deploy, mas para desenvolvimento facilita muito, ainda mais quando se trata de javascript onde tem nenhum padrão de pacotes globais. e eles tem muitos conflitos entre si.
